"use client";

import React, { useEffect, useRef } from "react";

export default function EconomicCalendarEmbed() {
  const containerRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (!containerRef.current) return;

    // Clear previous widget if any
    containerRef.current.innerHTML = "";

    const script = document.createElement("script");
    script.type = "text/javascript";
    script.async = true;
    script.src = "https://s3.tradingview.com/external-embedding/embed-widget-events.js";
    script.innerHTML = JSON.stringify({
      colorTheme: "light",
      isTransparent: false,
      width: "100%",
      height: 600,
      locale: "en",
      importanceFilter: "1,2,3",
      countryFilter: "us,eu,jp,gb,cn,au,nz,ca,ch",
    });
    containerRef.current.appendChild(script);

    return () => {
      if (containerRef.current) containerRef.current.innerHTML = "";
    };
  }, []);

  return (
    <section id="calendar" className="bg-white">
      <div className="container py-5 py-md-6">
        <div className="text-center mb-4">
          <h2 className="fw-bold mb-2">A real-time economic calendar</h2>
          <p className="text-secondary mb-0">Up-to-the-minute economic events, forecasts and actuals powered by TradingView.</p>
        </div>
        <div className="rounded-4 border shadow-sm p-3 p-md-4" style={{ borderColor: "#ecebf1", background: "linear-gradient(180deg,#ffffff,#fafafa)" }}>
          <div className="tradingview-widget-container">
            <div className="tradingview-widget-container__widget" ref={containerRef} />
            <div className="tradingview-widget-copyright text-center small text-secondary mt-3">
              <a href="https://www.tradingview.com/" rel="noopener nofollow" target="_blank">Track all markets on TradingView</a>
            </div>
          </div>
        </div>
        <p className="small text-secondary mt-3">
          <strong>Disclaimer:</strong> The information is authored by TradingView. All statements of opinion and any projections, forecasts, or statements relating to expectations regarding future events or the possible future performance of investments are generated by tools on the TradingView platform or are contributed by individual users of the platform. These views reflect the information and analyses available at the time of publication and are subject to change at any time. This information should not be construed as an offer, solicitation of an offer, or an invitation or inducement to engage in investment activity and cannot be relied upon as a representation that any particular transaction necessarily could have been or can be effected at the stated price.
        </p>
      </div>
    </section>
  );
}
