"use client";

import React from "react";

export default function EconomicCalendarInfoSections() {
  return (
    <section className="bg-white" id="learn">
      <div className="container py-5 py-md-6">
        {/* 1. Left text / Right image */}
        <div className="row align-items-center g-4 g-lg-5 mb-5">
          <div className="col-12 col-lg-6">
            <h2 className="fw-bold mb-3">Key Economic Events Calendar</h2>
            <p className="text-secondary">Stay updated on major economic announcements that move markets. Our economic calendar provides a comprehensive listing of important economic events and data releases worldwide. From central bank interest rate decisions to GDP reports, employment figures and more, these key events can impact financial markets and asset prices.</p>
            <p className="text-secondary">Updated in real-time, our calendar makes it easy to stay on top of high-impact events. We highlight market-moving releases in red, including details on the previous reading, forecasts, and potential market reaction. You can also filter by country and importance to focus on the events that matter most.</p>
          </div>
          <div className="col-12 col-lg-6">
            <div className="illustration-box rounded-4 border overflow-hidden">
              <img src="/images/econ-1.jpg" alt="Economic events overview" className="w-100 h-100 object-cover" />
            </div>
          </div>
        </div>

        {/* 2. Right text / Left image */}
        <div className="row align-items-center g-4 g-lg-5 mb-5 flex-lg-row-reverse">
          <div className="col-12 col-lg-6">
            <h2 className="fw-bold mb-3">A real-time economic calendar</h2>
            <p className="text-secondary">Imagine a calendar that provides up-to-the-minute information about important economic events and announcements that can impact financial markets. It serves you as a schedule of events, such as government reports, central bank decisions, and corporate earnings releases, and indicates their expected impact on currencies, stocks, commodities, and other assets.</p>
          </div>
          <div className="col-12 col-lg-6">
            <div className="illustration-box rounded-4 border overflow-hidden">
              <img src="/images/econ-2.jpg" alt="Real-time calendar" className="w-100 h-100 object-cover" />
            </div>
          </div>
        </div>

        {/* 3. Left text / Right image */}
        <div className="row align-items-center g-4 g-lg-5">
          <div className="col-12 col-lg-6">
            <h2 className="fw-bold mb-3">The significance of an economic calendar</h2>
            <p className="text-secondary">By offering real-time updates, an economic calendar helps individuals and organizations anticipate market movements, manage risks, and seize opportunities, making them an invaluable resource for anyone involved in financial markets.</p>
            <p className="text-secondary">It is a necessary tool for making informed decisions in financial markets, as it offers insights into key data releases such as GDP reports, employment figures, inflation rates, and central bank meetings. This data, in turn, influences asset prices, currency exchange rates, and market sentiment. Moreover, businesses rely on the economic calendar to plan their strategies, allocate resources, and manage risks based on economic trends and forecasts.</p>
          </div>
          <div className="col-12 col-lg-6">
            <div className="illustration-box rounded-4 border overflow-hidden">
              <img src="/images/econ-3.jpg" alt="Significance of economic calendar" className="w-100 h-100 object-cover" />
            </div>
          </div>
        </div>

        <p className="small text-secondary mt-4">
          <strong>Disclaimer:</strong> The information is authored by TradingView. All statements of opinion and all projections, forecasts, or statements relating to expectations regarding future events or the possible future performance of investments are generated by tools on the TradingView platform or are contributed by individual users of the platform. These views reflect the information and analyses available at the time of publication and are subject to change at any time. This information should not be construed as an offer, solicitation of an offer, or an invitation or inducement to engage in investment activity and cannot be relied upon as a representation that any particular transaction necessarily could have been or can be effected at the stated price.
        </p>
      </div>

      <style jsx>{`
        .illustration-box { min-height: 280px; background: #f8f9fb; border-color: #ecebf1; box-shadow: 0 6px 18px rgba(17,24,39,.05); }
        .object-cover { object-fit: cover; object-position: center; display: block; }
        @media (min-width: 992px) { .illustration-box { min-height: 340px; } }
      `}</style>
    </section>
  );
}
